mohist:
  check_update: true
  lang: xx_XX
  custom_flags: aaaa bbbb
  disable_mods_blacklist: false
  disable_plugins_blacklist: false
  check_update_auto_download: false
  show_logo: true
  networkmanager:
    enable: false
    debug: false
    intercept: []
forge:
  modsblacklist:
    enable: false
    list: aaaa,bbbb
    kickmessage: Use of unauthorized mods
  modswhitelist:
    enable: false
    mods_number: 0
    list: minecraft,forge
    kickmessage: Use of unauthorized mods
  hidejoinmodslist: false
libraries_black_list: aaaaa;bbbbbb
