# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: 1.16.4 CI with Gradle

on:
  push:
    branches: [ 1.16.4 ]
  pull_request:
    branches: [ 1.16.4 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew setup
        ./gradlew mohistJar
